#
# .github/workflows/cleanup-workflows.yml
#
# Copyright 2021 Ching Chow, Jens A. Koch.

on:
  # This workflow runs at 00:00 daily.
  schedule:
  - cron: '0 0 * * *'  # GMT
  # You can manually run this workflow.
  workflow_dispatch:

# action: write is needed to clear the cache
permissions:
  actions: write

jobs:

# ---------------------------------------------------------------------------------------

  cleanup-workflows:

# ---------------------------------------------------------------------------------------

    name: "Clean Workflows"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: ✂ Remove cancelled or skipped workflow runs
        uses: actions/github-script@v6 # https://github.com/actions/github-script
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const cancelled = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100,
              status: 'cancelled'
            });
            const skipped = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100,
              status: 'skipped'
            });
            for (const response of [cancelled, skipped]) {
              for (const run of response.data.workflow_runs) {
                console.log(`[Deleting] Run id ${run.id} of '${run.name}' is a cancelled or skipped run.`);
                await github.rest.actions.deleteWorkflowRun({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: run.id
                });
              }
            }

      - name: ✂ Remove 14 days old workflows runs
        uses: actions/github-script@v6 # https://github.com/actions/github-script
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const days_to_expiration = 14;
            const ms_in_day = 86400000;
            const now = Date.now();
            const pages = 5;
            // list the workflows runs to remove here
            const workflows = [
              'build-on-windows.yml'
            ]
            let runs_to_delete = [];
            for (const workflow of workflows) {
              for (let page = 0; page < pages; page += 1) {
                const response = await github.rest.actions.listWorkflowRuns({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  workflow_id: workflow,
                  page: page,
                  per_page: 100
                });
                if (response.data.workflow_runs.length > 0) {
                  for (const run of response.data.workflow_runs) {
                    if (now - Date.parse(run.created_at) > ms_in_day * days_to_expiration) {
                      runs_to_delete.push([run.id, run.name]);
                    }
                  }
                }
              }
            }
            for (const run of runs_to_delete) {
              console.log(`[Deleting] Run id ${run[0]} of '${run[1]}' is older than ${days_to_expiration} days.`);
              try {
                await github.rest.actions.deleteWorkflowRun({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: run[0]
                });
              } catch (error) {
                // ignore errors
              }
            }

      - name: ✂ Remove runs of the cleanup workflow itself
        uses: actions/github-script@v6 # https://github.com/actions/github-script
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pages = 5;
            let runs_to_delete = [];
            for (let page = 0; page < pages; page += 1) {
              const response = await github.rest.actions.listWorkflowRuns({
                owner: context.repo.owner,
                page: page,
                per_page: 100,
                repo: context.repo.repo,
                workflow_id: 'cleanup-workflows.yml',
              });
              if (response.data.workflow_runs.length > 0) {
                for (const run of response.data.workflow_runs) {
                  runs_to_delete.push([run.id, run.name]);
                }
              }
            }
            for (const run of runs_to_delete) {
              console.log(`[Deleting] Run id ${run[0]} of '${run[1]}'.`);
              try {
                await github.rest.actions.deleteWorkflowRun({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: run[0]
                });
                } catch (error) {
                  // ignore errors
                }
            }

      - name: ✂ Remove 14 days old caches
        uses: actions/github-script@v6 # https://github.com/actions/github-script
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const days_to_expiration = 14;
            const ms_in_day = 86400000;
            const now = Date.now();
            try {
              const caches = await github.rest.actions.getActionsCacheList({
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
              if (caches.data.actions_caches.length > 0) {
                for (const cache of caches.data.actions_caches) {
                  // cache.created_at
                  const cacheCreationDate = new Date(cache.created_at);
                  const timeSinceCreation = now - cacheCreationDate.getTime();
                  const daysSinceCreation = timeSinceCreation / ms_in_day;
                  // cache.last_accessed_at
                  const lastAccessedDate = new Date(cache.last_accessed_at);
                  const timeSinceLastAccess = now - lastAccessedDate.getTime();
                  const daysSinceLastAccess = timeSinceLastAccess / ms_in_day;
                  // both older than
                  if (daysSinceCreation <= days_to_expiration && daysSinceLastAccess <= days_to_expiration) {
                    console.log(`[Deleting] Cache ID ${cache.id} is older than ${days_to_expiration} days.`);
                    try {
                      await github.rest.actions.deleteActionsCacheById({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        cache_id: cache.id,
                      })
                    } catch (error) {
                      // ignore errors
                      // console.log(`Failed to delete cache ${cache.key};\n\n${error}`);
                    }
                  }
              }
            } catch (error) {
              // ignore errors
              // console.log(`Failed to getActionsCacheList.\n\n${error}`);
            }